### ISSUE TITLE
Still can edit when [press shift + right click] in 1.1.0

### ISSUE THREAD

**Issue by ArctonLin** [mgmgmg-dev/LocketteFix#2]
Hi, 
My server is purpur 1.20.4 (build2134)
When user keep press shift then right click on the sign can still edit the sign.
Any suggestion how to solve it?

**Comment by mgmgmg-dev** [comment]
I'm sorry, this resource is no longer maintained. I would guess a PlayerInteractEvent would do the trick here. Feel free to make a pull request if you wish to fix this.
