### ISSUE TITLE
add 1.20.5 support

### ISSUE THREAD

**Issue by Raidware** [mgmgmg-dev/LocketteFix#3]
Pls add 1.20.5 support

**Comment by mgmgmg-dev** [comment]
This plugin has been discontinued. It was meant to be a temporary fix until the LocketteFix dev caught up.

EDIT: It should be compatible with new versions of the game though.

**Comment by Raidware** [comment]
> This plugin has been discontinued. It was meant to be a temporary fix until the LocketteFix dev caught up.
> 
> EDIT: It should be compatible with new versions of the game though.

can u suggest chest lock plugin?

**Comment by mgmgmg-dev** [comment]
There are plenty of options you can choose from. A quick Google search should bring up the most important ones.

**Comment by Raidware** [comment]
> There are plenty of options you can choose from. A quick Google search should bring up the most important ones.

I used a lot of chest lock plugin but none of them good as lockettepro
